image:
  - Visual Studio 2019

configuration:
  - Debug
  - Release

before_build:
  - cmd: mkdir build-%CONFIGURATION%
  - cmd: cmake . -B build-%CONFIGURATION%

build:
  project: build-%CONFIGURATION%\game.sln
  verbosity: minimal

after_build:
  - cmd: cd build-%CONFIGURATION% && cpack -G ZIP -C %CONFIGURATION%

cache:
  - Debug-build\_deps
  - Release-build\_deps

artifacts:
  - path: build-$(CONFIGURATION)\game-0.1.1-win64.zip
    name: $(CONFIGURATION)
