image:
  - Visual Studio 2019

configuration:
  - Debug
  - Release

before_build:
  - cmd: cmake --build deps\build --target install
  - cmd: mkdir build
  - cmd: cmake . -B build -DCMAKE_INSTALL_PREFIX=install

after_build:
  - cmd: cd build && cpack -G ZIP -C %CONFIGURATION%

build:
  verbosity: minimal

cache: deps\build

install:
  - mkdir deps\build
  - cmake -B deps\build deps -DCMAKE_INSTALL_PREFIX=install
  - cmake --build deps\build -C Release

artifacts:
  - path: build\game-0.1.1-win64.zip
    name: $(CONFIGURATION)
