image:
  - Visual Studio 2019

configuration:
  - Debug
  - Release

before_build:
  - cmd: mkdir $(CONFIGURATION)-build
  - cmd: cmake -B $(CONFIGURATION)-build -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

after_build:
  - cmd: cd $(CONFIGURATION)-build && cpack -G ZIP -C %CONFIGURATION%

build:
  verbosity: normal

cache: C:\Tools\vcpkg\installed

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - vcpkg install glfw3:x64-windows

artifacts:
  - path: $(CONFIGURATION)-build/game-0.1.1-win64.zip
    name: $(CONFIGURATION)
